## Preprocessed

In [1]:
import os
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from utils import data_report, boxplot, countplot, histograma
import numpy as np

ruta= os.getcwd()
df = pd.read_csv(ruta + '\\malware_sin_nulos2.csv', index_col=0)
df.head()

RtpStateBitfield  AVProductsInstalled  AVProductsEnabled   Platform  \
0               7.0                  1.0                1.0  windows10   
1               7.0                  1.0                1.0  windows10   
2               7.0                  2.0                1.0  windows10   
3               7.0                  1.0                1.0  windows10   
4               7.0                  1.0                1.0  windows10   

   Processor  OsBuild  OsSuite OsPlatformSubRelease  \
0          1    16299        1                  rs3   
1          1    16299        1                  rs3   
2          1    16299        1                  rs3   
3          1    17134        0                  rs4   
4          1    17134        0                  rs4   

                                          OsBuildLab SkuEdition  ...  \
0  16299.431.amd64fre.rs3_release_svc_escrow.1805...       Home  ...   
1          16299.15.amd64fre.rs3_release.170928-1534       Home  ...   
2  16299.431.amd64fre.rs3_release_svc_escrow.1805...       Home  ...   
3           17134.1.amd64fre.rs4_release.180410-1804        Pro  ...   
4           17134.1.amd64fre.rs4_release.180410-1804        Pro  ...   

   AppVersion_a  AppVersion_b  AppVersion_c  AvSigVersion_a AvSigVersion_b  \
0            18          1807         18075             273           1188   
1            12         16299            15             275           1669   
2            12         16299            15             251             42   
3            18          1807         18075             275            760   
4            18          1807         18075             275           1442   

   OsVer_Binary  OsVer_a  OsVer_b  Census_OSVersion_a  Census_OSVersion_b  
0             1        0        0               16299                 547  
1             1        0        0               17134                 286  
2             1        0        0               16299                 492  
3             1        0        0               17134                 228  
4             1        0        0               17134                 285  

[5 rows x 59 columns]

In [2]:
cat = ['Census_MDC2FormFactor', 'RtpStateBitfield', 'Platform', 'OsBuild', 'OsPlatformSubRelease', 'OsBuildLab', 'SkuEdition', 'Census_ProcessorCoreCount', 'Census_ChassisTypeName', 'Census_PowerPlatformRoleName', 'Census_OSBranch', 'Census_OSBuildNumber', 'Census_OSBuildRevision', 'Census_OSEdition', 'Census_OSSkuName', 'Census_OSInstallTypeName', 'Census_OSInstallLanguageIdentifier', 'Census_OSUILocaleIdentifier', 'Census_OSWUAutoUpdateOptionsName', 'Census_GenuineStateName', 'Census_ActivationChannel', 'Census_FlightRing', 'EngineVersion_b', 'AppVersion_a', 'AppVersion_b', 'AppVersion_c', 'AvSigVersion_b', 'OsVer_a', 'OsVer_b', 'Census_OSVersion_b']
num = ['AVProductsInstalled', 'AVProductsEnabled', 'Census_PrimaryDiskTotalCapacity','Census_SystemVolumeTotalCapacity', 'Census_TotalPhysicalRAM', 'Census_InternalPrimaryDiagonalDisplaySizeInInches', 'Census_InternalPrimaryDisplayResolutionHorizontal', 'Census_InternalPrimaryDisplayResolutionVertical', 'Census_InternalBatteryNumberOfCharges', 'EngineVersion_a', 'AvSigVersion_a', 'Census_OSVersion_a']
binaria = ['Processor', 'OsSuite', 'IsProtected', 'SMode', 'Firewall', 'UacLuaenable', 'Census_ProcessorManufacturerIdentifier', 'Census_PrimaryDiskTypeName', 'Census_HasOpticalDiskDrive', 'Census_OSArchitecture', 'Census_IsSecureBootEnabled', 'Census_IsVirtualDevice', 'Census_IsTouchEnabled', 'Census_IsAlwaysOnAlwaysConnectedCapable', 'Wdft_IsGamer', 'OsVer_Binary']
target= ['HasDetections']

The goal of preprocessing is to format the data so that future machine learning models can best interpret it. To do this, the values ​​in all columns will be modified.

In [3]:
df.columns

Index(['RtpStateBitfield', 'AVProductsInstalled', 'AVProductsEnabled',
       'Platform', 'Processor', 'OsBuild', 'OsSuite', 'OsPlatformSubRelease',
       'OsBuildLab', 'SkuEdition', 'IsProtected', 'SMode', 'Firewall',
       'UacLuaenable', 'Census_MDC2FormFactor', 'Census_ProcessorCoreCount',
       'Census_ProcessorManufacturerIdentifier',
       'Census_PrimaryDiskTotalCapacity', 'Census_PrimaryDiskTypeName',
       'Census_SystemVolumeTotalCapacity', 'Census_HasOpticalDiskDrive',
       'Census_TotalPhysicalRAM', 'Census_ChassisTypeName',
       'Census_InternalPrimaryDiagonalDisplaySizeInInches',
       'Census_InternalPrimaryDisplayResolutionHorizontal',
       'Census_InternalPrimaryDisplayResolutionVertical',
       'Census_PowerPlatformRoleName', 'Census_InternalBatteryNumberOfCharges',
       'Census_OSArchitecture', 'Census_OSBranch', 'Census_OSBuildNumber',
       'Census_OSBuildRevision', 'Census_OSEdition', 'Census_OSSkuName',
       'Census_OSInstallTypeName', 'Census_

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 49999
Data columns (total 59 columns):
 #   Column                                             Non-Null Count  Dtype  
---  ------                                             --------------  -----  
 0   RtpStateBitfield                                   50000 non-null  float64
 1   AVProductsInstalled                                50000 non-null  float64
 2   AVProductsEnabled                                  50000 non-null  float64
 3   Platform                                           50000 non-null  object 
 4   Processor                                          50000 non-null  int64  
 5   OsBuild                                            50000 non-null  int64  
 6   OsSuite                                            50000 non-null  int64  
 7   OsPlatformSubRelease                               50000 non-null  object 
 8   OsBuildLab                                         50000 non-null  object 
 9   SkuEdition 

In [ ]:
#Preprocessing categorical columns
#le = LabelEncoder()
#p =le.fit_transform(df['Platform'])

In [6]:
#p =pd.Series(p)
#p.value_counts()

In [ ]:
#Apply a Label Encoder to all columns

label_encoder = {}

for i in cat:
    le = LabelEncoder()
    df[i] = le.fit_transform(df[i])
    label_encoder[i] = le

In [8]:
df.head()

RtpStateBitfield  AVProductsInstalled  AVProductsEnabled  Platform  \
0                 4                  1.0                1.0         0   
1                 4                  1.0                1.0         0   
2                 4                  2.0                1.0         0   
3                 4                  1.0                1.0         0   
4                 4                  1.0                1.0         0   

   Processor  OsBuild  OsSuite  OsPlatformSubRelease  OsBuildLab  SkuEdition  \
0          1        6        1                     3           6           4   
1          1        6        1                     3           4           4   
2          1        6        1                     3           6           4   
3          1        7        0                     4           7           6   
4          1        7        0                     4           7           6   

   ...  AppVersion_a  AppVersion_b  AppVersion_c  AvSigVersion_a  \
0  ...            14             8            59             273   
1  ...             8            14             3             275   
2  ...             8            14             3             251   
3  ...            14             8            59             275   
4  ...            14             8            59             275   

   AvSigVersion_b  OsVer_Binary  OsVer_a  OsVer_b  Census_OSVersion_a  \
0            1023             1        0        0               16299   
1            1369             1        0        0               17134   
2              35             1        0        0               16299   
3             665             1        0        0               17134   
4            1203             1        0        0               17134   

   Census_OSVersion_b  
0                  76  
1                  48  
2                  69  
3                  41  
4                  47  

[5 rows x 59 columns]

Categorical variables that had numbers now continue to contain numbers, but they are random. It is necessary to provide them with statistical meaning so that the algorithm can interpret them.

In [9]:
#One hot encoding Ejemplo
data = {
    'category' : ['A','B','A','C','B'],
    'value1' : [1,2,3,4,5],
    'value2': [10,20,30,40,50]
}

df_ =pd.DataFrame(data)
df_ = pd.get_dummies(df_, columns=['category'], drop_first=True)
df_

value1  value2  category_B  category_C
0       1      10       False       False
1       2      20        True       False
2       3      30       False       False
3       4      40       False        True
4       5      50        True       False

In [ ]:
#Escaler Example
data = np.array([
    [1,2,9],
    [2,3,300],
    [3,4,505]])

df2 = pd.DataFrame(data)

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df2)
df2_s = pd.DataFrame(scaled_data)
print(f'{scaled_data} \n {df2} \n {df2_s}')

[[-1.22474487 -1.22474487 -1.28908697]
 [ 0.          0.          0.14086592]
 [ 1.22474487  1.22474487  1.14822105]] 
    0  1    2
0  1  2    9
1  2  3  300
2  3  4  505 
           0         1         2
0 -1.224745 -1.224745 -1.289087
1  0.000000  0.000000  0.140866
2  1.224745  1.224745  1.148221


In [ ]:
#Example MinMaxEscaler

data = np.array([
    [1,2,9],
    [2,3,300],
    [3,4,505]])

df_3 = pd.DataFrame(data)

#A parameter can be added to the method to change the range
minmax_sacaler = MinMaxScaler(feature_range=(-1,1))
minmax_sacaler_data = minmax_sacaler.fit_transform(df_3)
df_3minmax = pd.DataFrame(minmax_sacaler_data)

print(f'{df_3} \n {df_3minmax}')

   0  1    2
0  1  2    9
1  2  3  300
2  3  4  505 
      0    1         2
0 -1.0 -1.0 -1.000000
1  0.0  0.0  0.173387
2  1.0  1.0  1.000000


As a final preprocessing step, a Pipeline will be made

In [14]:
from sklearn.base import BaseEstimator, TransformerMixin 
from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

from sklearn.preprocessing import LabelEncoder, MinMaxScaler, FunctionTransformer

In [ ]:
#Create clase

def label_encoder(df):
    return df.apply(LabelEncoder().fit_transform)

class GetDummiesTransformer(BaseEstimator, TransformerMixin):

    def __init__(self, drop_first=True):
        self.drop_first = drop_first 
    
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return pd.get_dummies(X, drop_first=self.drop_first)
    
preprocesor = ColumnTransformer(
    transformers=[
        ('label', FunctionTransformer(label_encoder, validate=False), cat),
        ('onehot', GetDummiesTransformer(),cat),
        ('scaler', MinMaxScaler(), num)
    ],
    remainder='passthrough'
)

pipeline= Pipeline(
    steps=[
        ('preprocesor',preprocesor),
    ]
)

df_preprocesado = pipeline.fit_transform(df)

df_4 = pd.DataFrame(df_preprocesado)
df_4.head()

0    1    2    3    4    5    6    7    8    9   ...   79   80   81   82  \
0  5.0  4.0  0.0  6.0  3.0  6.0  4.0  2.0  4.0  1.0  ...  1.0  0.0  1.0  0.0   
1  2.0  4.0  0.0  6.0  3.0  4.0  4.0  3.0  2.0  0.0  ...  1.0  0.0  1.0  1.0   
2  5.0  4.0  0.0  6.0  3.0  6.0  4.0  1.0  6.0  1.0  ...  1.0  0.0  1.0  1.0   
3  2.0  4.0  0.0  7.0  4.0  7.0  6.0  5.0  2.0  0.0  ...  0.0  0.0  1.0  0.0   
4  5.0  4.0  0.0  7.0  4.0  7.0  6.0  4.0  6.0  1.0  ...  0.0  0.0  1.0  1.0   

    83   84   85   86   87   88  
0  0.0  0.0  0.0  0.0  1.0  1.0  
1  0.0  0.0  0.0  0.0  0.0  1.0  
2  0.0  0.0  0.0  0.0  1.0  1.0  
3  0.0  0.0  0.0  0.0  0.0  1.0  
4  0.0  0.0  0.0  0.0  1.0  1.0  

[5 rows x 89 columns]

In [16]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 89 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       50000 non-null  float64
 1   1       50000 non-null  float64
 2   2       50000 non-null  float64
 3   3       50000 non-null  float64
 4   4       50000 non-null  float64
 5   5       50000 non-null  float64
 6   6       50000 non-null  float64
 7   7       50000 non-null  float64
 8   8       50000 non-null  float64
 9   9       50000 non-null  float64
 10  10      50000 non-null  float64
 11  11      50000 non-null  float64
 12  12      50000 non-null  float64
 13  13      50000 non-null  float64
 14  14      50000 non-null  float64
 15  15      50000 non-null  float64
 16  16      50000 non-null  float64
 17  17      50000 non-null  float64
 18  18      50000 non-null  float64
 19  19      50000 non-null  float64
 20  20      50000 non-null  float64
 21  21      50000 non-null  float64
 22